export { useAuthService, AuthProvider } from './auth/auth.service'
export { useCustomerService } from './customer/customer.service'
export { useWalletService, WalletProvider } from './wallet/wallet.service'
export { useLoadingService } from './loading/loading.service'
export { useShareService } from './share/share.service'
